# Generated by Django 6.0.6 on 2026-06-24 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gejala',
            fields=[
                ('kode_gejala', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nama_gejala', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'gejala',
            },
        ),
        migrations.CreateModel(
            name='Penyakit',
            fields=[
                ('id_penyakit', models.AutoField(primary_key=True, serialize=False)),
                ('nama_penyakit', models.CharField(max_length=100)),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('penanganan', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'penyakit',
            },
        ),
        migrations.CreateModel(
            name='RelasiPenyakitGejala',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mb', models.DecimalField(decimal_places=2, max_digits=3)),
                ('md', models.DecimalField(decimal_places=2, max_digits=3)),
                ('cf_pakar', models.DecimalField(decimal_places=2, max_digits=3)),
                ('id_penyakit', models.ForeignKey(db_column='id_penyakit', on_delete=django.db.models.deletion.CASCADE, to='pengetahuan.penyakit')),
                ('kode_gejala', models.ForeignKey(db_column='kode_gejala', on_delete=django.db.models.deletion.CASCADE, to='pengetahuan.gejala')),
            ],
            options={
                'db_table': 'relasi_penyakit_gejala',
            },
        ),
    ]
