# Generated by Django 6.0.6 on 2026-06-24 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pengetahuan', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id_diagnosis', models.AutoField(primary_key=True, serialize=False)),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('id_user', models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'diagnosis',
            },
        ),
        migrations.CreateModel(
            name='DetailDiagnosis',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cf_user', models.DecimalField(decimal_places=2, max_digits=3)),
                ('cf_kombinasi', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('kode_gejala', models.ForeignKey(db_column='kode_gejala', on_delete=django.db.models.deletion.CASCADE, to='pengetahuan.gejala')),
                ('id_diagnosis', models.ForeignKey(db_column='id_diagnosis', on_delete=django.db.models.deletion.CASCADE, to='diagnosis.diagnosis')),
            ],
            options={
                'db_table': 'detail_diagnosis',
            },
        ),
        migrations.CreateModel(
            name='HasilDiagnosis',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cf_final', models.DecimalField(decimal_places=4, max_digits=5)),
                ('ranking', models.IntegerField()),
                ('id_diagnosis', models.ForeignKey(db_column='id_diagnosis', on_delete=django.db.models.deletion.CASCADE, to='diagnosis.diagnosis')),
                ('id_penyakit', models.ForeignKey(db_column='id_penyakit', on_delete=django.db.models.deletion.CASCADE, to='pengetahuan.penyakit')),
            ],
            options={
                'db_table': 'hasil_diagnosis',
            },
        ),
    ]
