# Generated by Django 6.0.6 on 2026-06-24 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diagnosis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiwayatChat',
            fields=[
                ('id_chat', models.AutoField(primary_key=True, serialize=False)),
                ('pertanyaan', models.TextField()),
                ('jawaban', models.TextField(blank=True, null=True)),
                ('waktu', models.DateTimeField(auto_now_add=True)),
                ('id_diagnosis', models.ForeignKey(db_column='id_diagnosis', on_delete=django.db.models.deletion.CASCADE, to='diagnosis.diagnosis')),
            ],
            options={
                'db_table': 'riwayat_chat',
            },
        ),
    ]
